### ISSUE TITLE
sample methyaltion levels

### ISSUE THREAD

**Issue by shruti3009** [FlorianErger/cfNOMe#2]
Hi Florian, 
I am trying to run your deconvolution script on my bismark methylation extraction file (.bedgraph or CX-report). Can you please tell me how have you created the sample methylation bed file? To be more precise, how have you clustered those loci on chromosome level under specific CpG annotation for your healthy sample?  

Moreover, can you suggest any other source to download a reference methylation level file for whole-genome CpG loci? 

Thank you.

**Comment by FlorianErger** [comment]
Hi Shruti,

to reformat the .bedgraph Bismark output for use with the deconvolution script, I recommend something like: 

`zcat /path/to/bismark.bedGraph.gz | awk '{if(NR>1){print "chr"$1"\t"$2"\t"$3"\tid-"NR-1"\t"$4/100}}' | sort-bed - | bedmap --echo --delim '\t' --mean /path/to/CpG_loci_to_be_studied.bed - > average_methylation_at_loci_of_interest.bed`

Depending on the .fasta you used for the alignment, you may or may not need to add the "chr" back in the `awk` step.

The `bedmap` part of the pipe does the summarizing for the regions from your `CpG_loci_to_be_studied.bed` and calculates the mean. In the cfNOMe 'Example_data' folder, the `CpG_loci.bed` contains those differentially methylated regions from the Moss et al. publication. If you want to study different regions, you can simply generate your own "target CpG" bed (with tab-separated columns chromosome/start/end/region_identifier) and plug that in.

As for references, there are a lot of whole genome bisulfite tracks for different tissues at 
http://www.roadmapepigenomics.org/
and
https://epigenomesportal.ca/ihec/index.html
which may or may not be suitable for your specific research project. You will have to try it out.

We are also working on generating some more whole genome tissue-specific methylation references, but that is ongoing.
Hope this answers your questions!
Best,
Florian

**Comment by shruti3009** [comment]
Hi Florian,
Thank you for your response. What I understood from your explanation, average_methylation_at_loci_of_interest.bed, is same as the Sample_methylation_levels.bed file used in the command below?
`python3 methylation_deconvolution.py Example_data/Methylation/Reference_tissue_methylation.bed Example_data/Methylation/Sample_methylation_levels.bed --ineq --verbose`

Please kindly confirm.

**Comment by FlorianErger** [comment]
Hi Shruti,

correct!

**Comment by shruti3009** [comment]
Hi Florian, 
Thanks for confirming!
